### ISSUE TITLE
Why AdvancedSharpAdbClient achieved? 

### ISSUE THREAD

**Issue by wherewhere** [yungd1plomat/RubberPredictor#3]
If you don't want to continue to maintain that project, could you let me do it?
@yungd1plomat

**Comment by yungd1plomat** [comment]
yes, you can fork it and continue to develop
@wherewhere

**Comment by wherewhere** [comment]
Please add me so that I can publish new releases. @yungd1plomat 
![Screenshot_20221220-171415.jpg](https://user-images.githubusercontent.com/27689196/208629332-1625a049-a4e9-4065-b84f-6aaf0f35d30d.jpg)

**Comment by yungd1plomat** [comment]
> Please add me so that I can publish new releases. @yungd1plomat ![Screenshot_20221220-171415.jpg](https://user-images.githubusercontent.com/27689196/208629332-1625a049-a4e9-4065-b84f-6aaf0f35d30d.jpg)

pending invite

**Comment by yungd1plomat** [comment]
unarchived rep and added you to collaborators

**Comment by wherewhere** [comment]
Thanks!
